# Generated by Django 5.2.4 on 2025-08-07 22:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LightningTalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_name', models.CharField(help_text='Full name of the speaker', max_length=200)),
                ('email', models.EmailField(help_text='Contact email for the speaker', max_length=254)),
                ('title', models.CharField(help_text='Title of the lightning talk', max_length=300)),
                ('description', models.TextField(blank=True, help_text='Brief description of the talk (optional)')),
                ('is_accepted', models.BooleanField(default=False, help_text='Whether the talk has been accepted')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the talk was proposed')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time the proposal was updated')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the talk was reviewed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the proposal (not shown to speaker)')),
            ],
            options={
                'verbose_name': 'Lightning Talk',
                'verbose_name_plural': 'Lightning Talks',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
